server:
  port: 8821

spring:
  datasource:
    username: root
    password: Qinkang368
    url: jdbc:mysql://sh-cynosdbmysql-grp-gt0q8bdg.sql.tencentcdb.com:27950/PRS?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
  # Redis数据源
  redis:
    database: 0
    host: 124.221.157.240
    port: 6379
    timeout: 3000ms
    password: 123456

logging:
  level:
    root: info
    com.ittime.PRS: debug