create table tbl_goods_append
(
    goods_id                 bigint(19)                 not null comment '商品ID'
        primary key,
    goods_name               varchar(64)                not null comment '商品名称',
    goods_tag                varchar(64)                null comment '商品分类',
    goods_brand              varchar(64)                null comment '商品品牌',
    goods_img                varchar(255)               null comment '商品图片',
    shop_img                 varchar(255)               null comment '店铺图片',
    shop                     varchar(64)                null comment '店铺',
    price                    int(10)                    null comment '售价',
    original_price           int(10)                    null comment '原价 20170719 sanrenhe',
    goods_sales              int(16)                    null comment '销量',
    playback_volume          bigint(19)                 null comment '商品总播放（浏览）量',
    related_video            bigint(19)                 null comment '关联视频数',
    related_video_digg_count bigint(19)                 null comment '商品关联视频点赞总数 2020719新增字段',
    related_streamer         bigint(19)                 null comment '关联博主数',
    increase_day_playback    bigint(19)                 null comment '商品日浏览量增量',
    increase_day_sales       bigint(19)                 null comment '日销量增量',
    increase_day_revideo     bigint(19)                 null comment '每日增长关联视频数',
    increase_day_relabro     bigint(19)                 null comment '每日增长关联博主数',
    hot_degree               bigint(19)                 null comment '热度',
    rank_trend               int(10)                    null comment '排行榜上升趋势',
    playback_trend           double(11, 2)              null comment '浏览量趋势',
    shop_trend               int(10)                    null comment '店铺排行榜上升趋势',
    create_time              datetime                   null comment '创建时间',
    modified_time            datetime                   null comment '修改时间',
    deleted                  tinyint unsigned default 0 null comment '逻辑删除标识（0为否，1为是）'
)
    charset = utf8;

create index product_id
    on tbl_goods_append (goods_id);

INSERT INTO linglingbo.tbl_goods_append (goods_id, goods_name, goods_tag, goods_brand, goods_img, shop_img, shop, price, original_price, goods_sales, playback_volume, related_video, related_video_digg_count, related_streamer, increase_day_playback, increase_day_sales, increase_day_revideo, increase_day_relabro, hot_degree, rank_trend, playback_trend, shop_trend, create_time, modified_time, deleted) VALUES (1366889751158784, '苹果MacBookPro2018', '手机数码', 'Apple', 'AppleMacPro.jpg', 'Apple.jpg', 'Apple（中国大陆）官方旗舰店', 10988, 10000, 1002, 362, 21, 4110, 11, 6, 26, null, null, 5645, -1, 62.4, 2, null, null, 0);
INSERT INTO linglingbo.tbl_goods_append (goods_id, goods_name, goods_tag, goods_brand, goods_img, shop_img, shop, price, original_price, goods_sales, playback_volume, related_video, related_video_digg_count, related_streamer, increase_day_playback, increase_day_sales, increase_day_revideo, increase_day_relabro, hot_degree, rank_trend, playback_trend, shop_trend, create_time, modified_time, deleted) VALUES (1366890482737152, '小米10', '手机数码', '小米', 'xiaomi10.jpg', 'MI.jpg', '小米商城', 3999, 3000, 163000, 7894565, 82, 200, 40, 1000, 200, null, null, 3005000, 1, 16.1, 1, null, null, 0);
INSERT INTO linglingbo.tbl_goods_append (goods_id, goods_name, goods_tag, goods_brand, goods_img, shop_img, shop, price, original_price, goods_sales, playback_volume, related_video, related_video_digg_count, related_streamer, increase_day_playback, increase_day_sales, increase_day_revideo, increase_day_relabro, hot_degree, rank_trend, playback_trend, shop_trend, create_time, modified_time, deleted) VALUES (1366890975518720, '小米10pro', '手机数码', '小米', 'xiaomi10pro.jpg', 'MI.jpg', '小米商城', 5999, 5000, 99999, 12345678, 1234, 124, 1234, 12, 12, 54, 36, 1233, -2, 15.11, 5, null, null, 0);
INSERT INTO linglingbo.tbl_goods_append (goods_id, goods_name, goods_tag, goods_brand, goods_img, shop_img, shop, price, original_price, goods_sales, playback_volume, related_video, related_video_digg_count, related_streamer, increase_day_playback, increase_day_sales, increase_day_revideo, increase_day_relabro, hot_degree, rank_trend, playback_trend, shop_trend, create_time, modified_time, deleted) VALUES (1367819676016640, '纽西之谜防晒霜', '护肤', '纽西之谜', 'niuxi.jpg', 'geoskincare.jpg', 'geoskicare纽西之谜旗舰店', 299, 200, 254000, 884596, 156, 101, 166, 289, 266, null, null, 6902444, 5, -1.03, 3, null, null, 0);
INSERT INTO linglingbo.tbl_goods_append (goods_id, goods_name, goods_tag, goods_brand, goods_img, shop_img, shop, price, original_price, goods_sales, playback_volume, related_video, related_video_digg_count, related_streamer, increase_day_playback, increase_day_sales, increase_day_revideo, increase_day_relabro, hot_degree, rank_trend, playback_trend, shop_trend, create_time, modified_time, deleted) VALUES (1367952345071616, 'Mac魅可', '彩妆', '魅可', 'mac.jpg', 'MAC.jpg', 'Mac魅可官方旗舰店', 298, 200, 235000, 487565, 225, 4244, 206, 200, 165, null, null, 452689, -3, 2.55, 2, null, null, 0);
INSERT INTO linglingbo.tbl_goods_append (goods_id, goods_name, goods_tag, goods_brand, goods_img, shop_img, shop, price, original_price, goods_sales, playback_volume, related_video, related_video_digg_count, related_streamer, increase_day_playback, increase_day_sales, increase_day_revideo, increase_day_relabro, hot_degree, rank_trend, playback_trend, shop_trend, create_time, modified_time, deleted) VALUES (1368039029825536, '苹果Mac', '手机数码', 'Apple', 'AppleMac.jpg', 'Apple.jpg', 'Apple（中国大陆）官方旗舰店', 4999, 4000, 2564, 456, 33, 1441, 59, 9, 31, null, null, null, 1, 159.3, -2, null, null, 0);
INSERT INTO linglingbo.tbl_goods_append (goods_id, goods_name, goods_tag, goods_brand, goods_img, shop_img, shop, price, original_price, goods_sales, playback_volume, related_video, related_video_digg_count, related_streamer, increase_day_playback, increase_day_sales, increase_day_revideo, increase_day_relabro, hot_degree, rank_trend, playback_trend, shop_trend, create_time, modified_time, deleted) VALUES (1368039110565888, '小米10pro', '手机数码', '小米', 'xiaomi10pro.jpg', 'MI.jpg', '小米商城', 4999, 4000, 152000, 3896556, 32, 100, 20, 65, 36, 45, 30, 25669, 4, 12.23, 4, null, null, 0);
INSERT INTO linglingbo.tbl_goods_append (goods_id, goods_name, goods_tag, goods_brand, goods_img, shop_img, shop, price, original_price, goods_sales, playback_volume, related_video, related_video_digg_count, related_streamer, increase_day_playback, increase_day_sales, increase_day_revideo, increase_day_relabro, hot_degree, rank_trend, playback_trend, shop_trend, create_time, modified_time, deleted) VALUES (1368039110565971, 'iphone12', '手机数码', '苹果', 'iphonex.jpg', 'Apple.jpg', 'Apple（中国大陆）官方旗舰店', 7999, 7000, 113535, 113, 12, 11, 157, 1, 1, 45, 30, 5643543, 4, 13.22, 3, null, null, 0);
INSERT INTO linglingbo.tbl_goods_append (goods_id, goods_name, goods_tag, goods_brand, goods_img, shop_img, shop, price, original_price, goods_sales, playback_volume, related_video, related_video_digg_count, related_streamer, increase_day_playback, increase_day_sales, increase_day_revideo, increase_day_relabro, hot_degree, rank_trend, playback_trend, shop_trend, create_time, modified_time, deleted) VALUES (1368039110565999, 'iphoneX', '手机数码', '苹果', 'iphonex.jpg', 'Apple.jpg', 'Apple（中国大陆）官方旗舰店', 3999, 3000, 65132, 5465, 12, 22, 123, 5, 51, 45, 30, 54654, 4, 16.22, 3, null, null, 0);
INSERT INTO linglingbo.tbl_goods_append (goods_id, goods_name, goods_tag, goods_brand, goods_img, shop_img, shop, price, original_price, goods_sales, playback_volume, related_video, related_video_digg_count, related_streamer, increase_day_playback, increase_day_sales, increase_day_revideo, increase_day_relabro, hot_degree, rank_trend, playback_trend, shop_trend, create_time, modified_time, deleted) VALUES (1368039110567963, 'iphone13', '手机数码', '苹果', 'iphonex.jpg', 'Apple.jpg', 'Apple（中国大陆）官方旗舰店', 8999, 8000, 123456465, 179, 12, 5441, 54631, 33, 79, 12, 456, 197846, 2, 9.73, 2, null, null, 0);
INSERT INTO linglingbo.tbl_goods_append (goods_id, goods_name, goods_tag, goods_brand, goods_img, shop_img, shop, price, original_price, goods_sales, playback_volume, related_video, related_video_digg_count, related_streamer, increase_day_playback, increase_day_sales, increase_day_revideo, increase_day_relabro, hot_degree, rank_trend, playback_trend, shop_trend, create_time, modified_time, deleted) VALUES (1373092170776576, 'iphone8', '手机数码', '苹果', 'iphonex.jpg', 'Apple.jpg', 'Apple（中国大陆）官方旗舰店', 6999, 6000, 1231564, 1235464, 12, 5441, 59, 9, 31, 54, 30, 154876, 4, 9.62, 2, null, null, 0);
INSERT INTO linglingbo.tbl_goods_append (goods_id, goods_name, goods_tag, goods_brand, goods_img, shop_img, shop, price, original_price, goods_sales, playback_volume, related_video, related_video_digg_count, related_streamer, increase_day_playback, increase_day_sales, increase_day_revideo, increase_day_relabro, hot_degree, rank_trend, playback_trend, shop_trend, create_time, modified_time, deleted) VALUES (1373092212883456, 'iphoneSE', '手机数码', '苹果', 'iphonex.jpg', 'Apple.jpg', 'Apple（中国大陆）官方旗舰店', 4999, 4200, 7835331, 1315465, 12, 3661, 10, 5, 31, 40, 22, 15876, 3, 2.72, 2, null, null, 0);
INSERT INTO linglingbo.tbl_goods_append (goods_id, goods_name, goods_tag, goods_brand, goods_img, shop_img, shop, price, original_price, goods_sales, playback_volume, related_video, related_video_digg_count, related_streamer, increase_day_playback, increase_day_sales, increase_day_revideo, increase_day_relabro, hot_degree, rank_trend, playback_trend, shop_trend, create_time, modified_time, deleted) VALUES (1373092437704704, 'iphoneSE', '手机数码', '苹果', 'iphonex.jpg', 'Apple.jpg', 'Apple（中国大陆）官方旗舰店', 4999, 4200, 7873543, 112345, 12, 1546748, 212, 1, 154, 22, 22, 1587, 3, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_goods_append (goods_id, goods_name, goods_tag, goods_brand, goods_img, shop_img, shop, price, original_price, goods_sales, playback_volume, related_video, related_video_digg_count, related_streamer, increase_day_playback, increase_day_sales, increase_day_revideo, increase_day_relabro, hot_degree, rank_trend, playback_trend, shop_trend, create_time, modified_time, deleted) VALUES (1373092536532992, 'huaweiMate20', '手机数码', '华为', 'huawei.jpg', 'huawei.jpg', '华为公司', 4999, 4000, 786334, 1123546, 12, 1587465, 212, 9, 123, 14, 79, 5432187, 2, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_goods_append (goods_id, goods_name, goods_tag, goods_brand, goods_img, shop_img, shop, price, original_price, goods_sales, playback_volume, related_video, related_video_digg_count, related_streamer, increase_day_playback, increase_day_sales, increase_day_revideo, increase_day_relabro, hot_degree, rank_trend, playback_trend, shop_trend, create_time, modified_time, deleted) VALUES (1373092544888832, 'huaweiMate30', '手机数码', '华为', 'huawei.jpg', 'huawei.jpg', '华为公司', 3999, 4000, 545487, 5468768, 12, 448676, 212, 6, 213, 14, 5564, 5465465465, 2, 2.72, 2, null, null, 0);
INSERT INTO linglingbo.tbl_goods_append (goods_id, goods_name, goods_tag, goods_brand, goods_img, shop_img, shop, price, original_price, goods_sales, playback_volume, related_video, related_video_digg_count, related_streamer, increase_day_playback, increase_day_sales, increase_day_revideo, increase_day_relabro, hot_degree, rank_trend, playback_trend, shop_trend, create_time, modified_time, deleted) VALUES (1373092644986880, 'huaweiMate40', '手机数码', '华为', 'huawei.jpg', 'huawei.jpg', '华为公司', 6999, 6888, 54564, 154687, 12, 448676, 212, 6, 210, 14, 1546, 54646, 1, 1.33, 2, null, null, 0);
