create table tbl_streamer_append
(
    streamer_id          bigint(19)                 not null comment '主播ID'
        primary key,
    streamer_name        varchar(255)               null,
    industry             varchar(64)                null comment '分类',
    label                varchar(64)                null comment '标签',
    introduction         varchar(64)                null comment '博主简介',
    contact_information  varchar(32)                null comment '私人联系方式',
    cooperation          varchar(32)                null comment '合作',
    blog                 varchar(32)                null comment '围脖',
    account_type         int(3)                     not null comment '账号类型（1-个人、2-企业、3-电商）',
    blue_v               int(3)                     not null,
    total_fans           bigint(19)                 null,
    total_videos         bigint(19)                 null,
    total_likes          bigint(19)                 null,
    total_shares         bigint(19)                 null,
    total_comments       bigint(19)                 null,
    star_index           decimal(20, 2)             null,
    blue_v_rank_rise     bigint(19)                 null comment '蓝V排行上升 正为上升 负为下降 20200719 sanrenhe',
    region_rank_rise     bigint(19)                 null comment '地区排行上升 正为上升 负为下降 20200719 sanrenhe',
    fans_rank_rise       bigint(19)                 null comment '涨粉排行上升 正为上升 负为下降 20200719 sanrenhe',
    industry_rank_rise   bigint(19)                 null comment '行业排行上升 正为上升 负为下降 20200719 sanrenhe',
    month_digg_rank_rise bigint(19)                 null comment '近30天点赞增量 正为上升 负为下降 20200719 sanrenhe',
    month_works          bigint(19)                 null comment '近30天作品数  20200722 sanrenhe',
    month_fans_rank_rise bigint(19)                 null comment '近30天粉丝增量 正为上升 负为下降 20200722 sanrenhe',
    portrait_province    varchar(60)                null comment '粉丝画像主要地域（省级行政区） 20200720 sanrenhe',
    portrait_city        varchar(60)                null comment '粉丝画像主要地域（地级市） 20200720 sanrenhe ',
    portrait_age         int(3)                     null comment '粉丝画像主要年龄 20200720 sanrenhe',
    portrait_sex         int(3)                     null comment '粉丝画像主要性别 （1-男、2-女） 20200720 sanrenhe',
    live_sales           bigint                     null comment '直播销量',
    frequency            int(5)                     null,
    create_time          datetime                   null comment '创建时间',
    modified_time        datetime                   null comment '修改时间',
    deleted              tinyint unsigned default 0 null comment '逻辑删除标识(0为否，1为是)',
    province             varchar(255)               null,
    city                 varchar(255)               null
)
    charset = utf8;

INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (1234567, null, '数码', '星座', '我是库里', '131313131', '123131', 'kuli', 1, 1, 11111, 1111, 11111, 11111, 11111, 11.10, 1, 1, 2, 1, 12, 8, 78, '浙江', '湖州市', 23, 1, 3200, 2, '浙江', '杭州', 0, null, null, null, null, null, null, null, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (7654321, null, '穿搭', '育儿', '我是库外', '2131313131', '1231313', 'kuwai', 2, 1, 22222, 2222, 22222, 22222, 22222, 22.10, -6, 4, -3, -1, 12, 78, 11, '浙江', '杭州市', 26, 2, 5642, 1, '浙江', '杭州', 0, null, null, null, null, null, null, null, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (31111111, null, '美食', '足球', '我是梅西', '1111111111', '1111111', 'meixi', 1, 1, 33333, 3333, 33333, 33333, 33333, 33.10, 0, 2, 1, 2, 11, 78, 45, '江苏', '盐城市', 16, 1, 1236, 0, '浙江', '杭州', 0, null, null, null, null, null, null, null, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (41234567, null, '数码', '星座', '我是库里', '131313131', '123131', 'kuli', 1, 1, 11112, 1112, 11112, 11112, 11112, 12.10, 0, 0, 12, 2, 2, 78, 425, '江苏', '南京市', 18, 2, 6954, 5, '浙江', '杭州', 0, null, null, null, null, null, null, null, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (51234567, null, '数码', '星座', '我是库里', '131313131', '123131', 'kuli', 1, 1, 11113, 1113, 11113, 11113, 11113, 13.10, 3, 1, -6, 3, 88, 78, 454, '上海', '徐汇区', 25, 1, 3366, 9, '浙江', '杭州', 1364916962402304, '2023-01-31 16:52:20', null, null, null, null, null, null, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (67654321, null, '穿搭', '育儿', '我是库外', '2131313131', '1231313', 'kuwai', 2, 1, 22223, 2223, 22223, 22223, 22223, 23.10, 4, 3, 5, 2, 9, 88, 24, '安徽', '马鞍山市', 22, 2, 1425, 4, '浙江', '杭州', 0, null, null, null, null, null, null, null, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (81234567, null, '数码', '星座', '我是库里', '131313131', '123131', 'kuli', 1, 1, 11112, 1112, 11112, 11112, 11112, 12.10, 0, 0, 12, 2, 401, 454, 22, '江苏', '南京市', 18, 2, 2594, 3, '浙江', '杭州', 0, null, null, null, null, null, null, null, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (1364916962402304, '毛毛光', '数码', '星座', '我是库里', '131313131', '123131', 'kuli', 1, 1, 11111, 1111, 11111, 11111, 11111, 11.10, 1, 1, 2, 1, 12, 8, 78, '浙江', '湖州市', 23, 1, 3200, 2, '广东省', '广州市', 1364916962402304, '2023-02-16 16:52:44', null, null, null, null, null, null, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (1364982471729152, '梅西', '美食', '足球', '我是梅西', '1111111111', '1111111', 'meixi', 1, 1, 33334, 3334, 33334, 33334, 33334, 34.10, 1, 4, -6, -3, 99, 87, 26, '福建', '宁德市', 20, 1, 669, 6, '浙江', '杭州', 0, null, null, null, null, null, null, null, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (1366909789347840, '周云熙', '美食', '星座', '我是美西', '111111', '333333', 'meixi', 1, 1, 2656487, 45643, 4876, 4631132, 13545, 13.31, 1, 4, 6, -3, 77, 55, 55, '浙江', '台州市', 12, 1, 2579, 2, '广东省', '深圳', 0, null, null, null, null, null, null, null, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (1366910520090624, '田小野', '穿搭', '育儿', '我是库外', '2131313131', '1231313', 'kuwai', 2, 1, 22222, 2222, 22222, 22222, 22222, 22.10, -6, 4, -3, -1, 12, 78, 11, '浙江', '杭州市', 26, 2, 5642, 1, '上海市', '上海市', 1364916962402304, '2023-02-01 16:52:15', null, null, null, null, null, null, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (1366910530576384, '川香秋月', '美食', '足球', '我是梅西', '1111111111', '1111111', 'meixi', 1, 1, 33333, 3333, 33333, 33333, 33333, 33.10, 0, 2, 1, 2, 11, 78, 45, '江苏', '盐城市', 16, 1, 1236, 0, '广东省', '东莞', 0, null, null, null, null, null, null, null, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (1366911297290240, '黄志远', '穿搭', '育儿', '我是眉笔', '2222222', '22222', 'meibi', 1, 1, 25643153, 1546, 789796, 51354654, 345654, 11.21, 1, 4, 6, -4, 66, 76, 46, '浙江', '杭州市', 12, 1, 2579, 2, '上海市', '上海市', 0, '2023-02-08 16:53:00', null, null, null, null, null, null, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (1366911892504576, '城七日记', '数码', '星座', '我是库里', '131313131', '123131', 'kuli', 1, 1, 11113, 1113, 11113, 11113, 11113, 13.10, 3, 1, -6, 3, 88, 78, 454, '上海', '徐汇区', 25, 1, 3366, 9, '广东省', '深圳', 1364916962402304, '2023-02-03 16:52:34', null, null, null, null, null, null, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (1366911899926528, 'boos何', '穿搭', '育儿', '我是库外', '2131313131', '1231313', 'kuwai', 2, 1, 22223, 2223, 22223, 22223, 22223, 23.10, 4, 3, 5, 2, 9, 88, 24, '安徽', '马鞍山市', 22, 2, 1425, 4, '广东省', '深圳', 0, null, null, null, null, null, null, null, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (1368388863582208, '小康总', '数码', '星座', '我是库里', '131313131', '123131', 'kuli', 1, 1, 11112, 1112, 11112, 11112, 11112, 12.10, 0, 0, 12, 2, 401, 454, 22, '江苏', '南京市', 18, 2, 2594, 3, '上海市', '上海市', 1364916962402304, '2023-02-07 16:52:30', null, null, null, null, null, null, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (1368390327246848, '吃不饱三人组', '美食', '足球', '我是梅西', '1111111111', '1111111', 'meixi', 1, 1, 33334, 3334, 33334, 33334, 33334, 34.10, 1, 4, -6, -3, 99, 87, 26, '福建', '宁德市', 20, 1, 669, 6, '广东省', '广州市', 0, null, null, null, null, null, null, null, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (1372999360520192, '乐天娱乐', '数码', '星座', '我是海平', '11123456', '13546', 'haiping', 1, 1, 6546, 35465, 546, 465, 46546546, 21.45, 1, 4, 5, -2, 88, 88, 88, '浙江', '绍兴市', 12, 2, 2497, 2, '上海市', '上海市', 0, null, '乐天娱乐', '乐天娱乐公司', 'www.letian.com', '吴乐天', '13842113422', '13842113422', null, 48, '2023-02-12 17:21:47', null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (1372999360520193, '邵子涛', '穿搭', '星座', '我是子韬', '222222', '154613', 'zitao', 1, 1, 13544, 54656, 135435, 135435, 1354654, 11.11, 1, 2, 5, 1, 67, 49, 72, '浙江', '绍兴市', 12, 1, 7943, 2, '上海市', '上海市', 1364916962402304, '2023-02-02 16:52:38', null, null, null, null, null, null, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (1372999360520194, '小象MCN', '美食', '足球', '我是欧文', '1111111', '222222', 'ouwen', 1, 1, 3334, 33546, 5465, 5646, 5644, 23.17, 1, 2, 6, -2, 88, 58, 456, '浙江', '南京市', 16, 1, 669, 5, '上海市', '上海市', 0, null, '小象MCN', '小象娱乐公司', 'www.smallxiang.com', '冯宇宁', '15233427856', '15233427856', null, 25, '2023-02-12 17:23:38', null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (1372999360520195, '月老板', '数码', '星座', '我是库里', '131313131', '123131', 'kuli', 1, 1, 11112, 1112, 11112, 11112, 11112, 12.10, 0, 0, 12, 2, 2, 78, 425, '江苏', '南京市', 18, 2, 6954, 5, '广东省', '广州市', 0, null, null, null, null, null, null, null, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (1372999360520196, '魏晓明', '数码', '足球', '我是欧文', '2222222', '22222', 'ouwen', 1, 1, 33334, 222222, 111111, 5644, 1315, 16.17, 2, 2, 5, -1, 79, 59, 23, '福建', '宁德市', 16, 1, 2425, 3, '广东省', '深圳', 0, null, null, null, null, null, null, null, null, null, null, null, 0);
INSERT INTO linglingbo.tbl_streamer_append (streamer_id, streamer_name, industry, label, introduction, contact_information, cooperation, blog, account_type, blue_v, total_fans, total_videos, total_likes, total_shares, total_comments, star_index, blue_v_rank_rise, region_rank_rise, fans_rank_rise, industry_rank_rise, month_digg_rank_rise, month_works, month_fans_rank_rise, portrait_province, portrait_city, portrait_age, portrait_sex, live_sales, frequency, province, city, authorize, authorize_time, mcn_name, company, website, contact, tel, wechat, email, sign_num, create_time, modified_time, deleted) VALUES (1372999360520197, '苏璐', '穿搭', '星座', '我是姚明', '3333333', '33333', 'yaoming', 1, 1, 222234, 546343, 13132155, 13456, 3546, 17.77, 2, 2, 4, -2, 88, 56, 456, '浙江', '宁德市', 16, 1, 2586, 2, '北京市', '北京市', 0, null, null, null, null, null, null, null, null, null, null, null, 0);
